# Generated by Django 2.0.7 on 2018-07-09 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('user_last_name', models.CharField(max_length=128)),
                ('user_birthday', models.CharField(max_length=20)),
                ('user_cellphone_number', models.CharField(max_length=15)),
                ('user_habilities', models.CharField(max_length=300)),
                ('user_usuario', models.OneToOneField(on_delete='Cascade', related_name='usuario_relacionado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user_name',),
            },
        ),
    ]
