# Generated by Django 2.0.7 on 2018-07-02 21:22

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ctsp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('user_last_name', models.CharField(max_length=128)),
                ('user_birthday', models.DateField()),
                ('user_cellphone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+\\d{2}\\s\\d{2}\\s\\d{9,12}$')])),
                ('user_habilities', models.TextField(max_length=300)),
                ('user_email', models.EmailField(max_length=128)),
                ('user_password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='project_final_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
