# Generated by Django 2.0.7 on 2018-07-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctsp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
