# Generated by Django 2.0.7 on 2018-07-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctsp', '0002_auto_20180702_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('project_name',)},
        ),
    ]
