# Generated by Django 2.0.7 on 2018-07-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctsp', '0003_auto_20180702_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('user_name',)},
        ),
    ]
