# Generated by Django 2.0.7 on 2018-07-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctsp', '0004_auto_20180702_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(to='ctsp.User'),
        ),
    ]
